config:
  SMTP_SERVER: letter.tpu.ru
  SMTP_PORT: 587
  SENDER_EMAIL: "rao6@tpu.ru"
  RECEIVER_EMAIL: "ave50@tpu.ru"
  CURRENCY_URL: https://v6.exchangerate-api.com/v6
  CBR_URL: http://www.cbr.ru/scripts/XML_daily.asp
  S3_URL: s3.timeweb.cloud
  S3_BUCKET_NAME: 27731d10-saina-rivals
  S3_CURRENCY_PREFIX: currency
  S3_FETCH_PREFIXES:
    - "rivals/"
    - "rivals_i/"
  SEND_TO:
    - telegram-user-id-565809356
scheduler:
  currency: "EUR"
  tasks:
    - name: "utair"
      enabled: true
      currency_type: "CBR"
      convert_type: "utair"
      convert_times:  # Список времен для конверсии
        - "default"
        - "3:01-utc"
        - "12:45-utc"
      time_ranges:   # Список диапазонов времени
        - "01:00-03:00-utc"
        - "13:00-15:00-utc"
      air_companies:
        - "WZ"
        - "U6"