config:
  currency-url: https://v6.exchangerate-api.com/v6
  s3-url: s3.timeweb.cloud
  s3-bucket-name: 27731d10-saina-rivals
  s3-currency-prefix: currency
  send_to:
    - telegram-user-id-565809356
scheduler:
  currency: "EUR"
  tasks:
    - name: "utair"
      enabled: true
      type: "utair"
      convert_times:  # Список времен для конверсии
        - "default"
        - "3:01-utc"
        - "12:45-utc"
      time_ranges:   # Список диапазонов времени
        - "01:00-03:00-utc"
        - "13:00-15:00-utc"
      air_companies:
        - "WZ"
        - "U6"