config:
  SMTP_SERVER: letter.tpu.ru
  SMTP_PORT: 587
  SENDER_EMAIL: "rao6@tpu.ru"
  RECEIVER_EMAIL: "ave50@tpu.ru"
  CURRENCY_URL: https://v6.exchangerate-api.com/v6
  CBR_URL: https://www.cbr.ru/scripts/XML_daily.asp
  NBRB_URL: https://api.nbrb.by/exrates/rates?periodicity=0
  S3_URL: s3.timeweb.cloud
  S3_BUCKET_NAME: 27731d10-saina-rivals
  S3_CURRENCY_PREFIX: currency
  S3_FETCH_PREFIXES:
    - "rivals/"
    - "rivals_i/"
  SEND_TO:
    - telegram-user-id-565809356
  CBR_MAIN_KEY: VunitRate
  CBR_CURRENCY_SEARCH_KEY: CharCode
  NBRB_CURRENCY_SEARCH_KEY: Cur_Abbreviation
scheduler:
  currency: "EUR"
  tasks:
    - name: "utair"
      enabled: true
      type: file_conversion # Конвертировать файлы
      currency_type: "CBR"
      convert_type: "utair" # Тип конвертации
      trigger_times:  # Список времен для конверсии
        - "default" # Сейчас
        - "3:01-utc"
        - "12:45-utc"
      time_ranges:   # Список диапазонов времени
        - "01:00-03:00-utc"
        - "13:00-15:00-utc"
      air_companies:
        - "WZ"
        - "U6"

    - name: "fetch_NBRB"
      enabled: true
      type: "currency_fetching" # Получить курс валют
      currency_type: "NBRB" # Получение курсов из НБ РБ
      trigger_times:
        - "default"
        - "00:00-utc"
        - "12:00-utc"

    - name: "fetch_CBR"
      enabled: true
      type: "currency_fetching"
      currency_type: "CBR" # Получение курсов из ЦБ РФ
      trigger_times:
        - "default"
        - "00:00-utc"
        - "12:00-utc"